### ISSUE TITLE
"Helm Dependency Update" got error message

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#142] opened 2018-03-28 07:59 UTC
when executing "Helm Dependency Update" we got below output in terminal. To solve this error, we need to run "helm serve" in bash.

Would that be better if the plugin gives a prompt message to remind user ?

![image](https://user-images.githubusercontent.com/4318793/38015872-cb6a20d4-329f-11e8-9293-2d2128431d48.png)

**Comment by bnookala** [comment] 2018-04-04 23:16
@songkaiape can you `cat` your `requirements.yaml` file and paste it here? I believe that connection refused message is expected to appear - I just ran `helm dependency update` on the phabricator chart to see what would happen:

```
$ helm dependency update
Hang tight while we grab the latest from your chart repositories...
...Unable to get an update from the "local" chart repository (http://127.0.0.1:8879/charts):
	Get http://127.0.0.1:8879/charts/index.yaml: dial tcp 127.0.0.1:8879: getsockopt: connection refused
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
...Successfully got an update from the "deis" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading mariadb from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

**Comment by songkaiape** [comment] 2018-04-08 02:34
@bnookala  Below is my requirement.yaml
```
dependencies:
  - name: redis
    version: 1.1.19
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: mongodb
    version: 0.4.28
    repository: https://kubernetes-charts.storage.googleapis.com
```

**Comment by itowlson** [comment] 2018-04-30 02:03
@technosophos @bacongobbler Is Bhargav correct that the the initial "Unable to get an update from local" is an expected output of Helm as it searches for an update source?  If so I think we can close this issue @songkaiape?

**Comment by bacongobbler** [comment] 2018-04-30 03:06
Yes, that error is expected by default due to the "local" repository which is set up for convenience purposes.

**Comment by itowlson** [comment] 2018-04-30 03:31
Thanks Matt.  Closing as expected behaviour (and out of the control of the extension!).

**Closed by itowlson** 2018-04-30 03:31 UTC
Labels: bug, question
