### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [Azure/vscode-kubernetes-tools#485] opened 2019-03-01 23:08 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-kubernetes-tools`
- Extension Version: `0.1.16`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\jk\ms-kubernetes-tools.vscode-kubernetes-tools-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by brendandburns** [comment] 2019-03-02 02:26
Can you add some more detail? What were you doing in the extension? What were you viewing?

(Also, the profile referred to in report would be useful)

Thanks!

**Comment by itowlson** [comment] 2019-03-05 01:49
Possible duplicate of #479, which went away after occurring once, though hard to be sure unless we have more details.  Sounds like I might need to look at what it's doing during startup.

**Comment by lstocchi** [comment] 2021-11-23 11:30
Should be resolved now as #586 was merged. Feel free to reopen it if you still face this issue. Thanks!!

**Closed by lstocchi** 2021-11-23 11:30 UTC
Labels: bug
