### ISSUE TITLE
No intelisense for Minio CRD

### ISSUE THREAD

**Issue by arianvp** [Azure/vscode-kubernetes-tools#835] opened 2020-11-05 19:37 UTC
Intelisense is working for all my CRDs except minio. But I can't figure out why it is not working.

The CRD in question is defined here: https://github.com/minio/operator/blob/master/operator-kustomize/crds/minio.min.io_tenants.yaml

It does seem to include a structured schema; just as the others. But Intelisense is not kicking in

Example config:

```yaml
## MinIO Tenant Definition
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
spec:
  image: minio/minio:RELEASE.2020-10-18T21-54-12Z
  imagePullPolicy: IfNotPresent
  podManagementPolicy: Parallel
  credsSecret:
    name: minio-creds-secret
  zone:
    - servers: 4
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: "local-path"
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  
```

**Comment by itowlson** [comment] 2021-01-28 03:54
Sorry for the late response.  Are you still seeing this problem?  I installed the Minio CRD and I am getting intellisense on your file, though I did reload the extension after installing the CRD (to force it to reread the cluster's OpenAPI document).  The funny thing is I am _not_ getting intellisense for `zone` or anything underneath it; it looks like the `zone` property might not be defined in the schema in the CRD.  (On the other hand, I'm not getting an error saying this element is invalid, but I think that's because the `spec` schema doesn't specify `additionalProperties: false` so it's allowing arbitrary additional properties.)

**Comment by itowlson** [comment] 2021-01-28 03:59
We have also seen an issue where CRD intellisense does not work for files that are already open when VS Code starts up, I think because VS Code asks us for a schema before we've had a chance to talk to the cluster (and then won't let us amend our answer when we _have_ talked to the cluster).  So, just to diagnose if this is part of the issue, you could also try opening VS Code with your Tenant YAML file closed; then switch the the Kubernetes tab in the left hand bar; _then_ open the Tenant YAML file.  If this works but "normal" ways don't, let us know - maybe we can do some caching or something to improve matters.

**Comment by arianvp** [comment] 2021-01-28 12:35
The `zone` field was renamed in newer versions of the CRD. I'll check back with your instructions if I can still reproduce

**Comment by bacongobbler** [comment] 2021-03-15 15:36
Hey. Just checking in to see if you were able to reproduce ^

**Comment by lstocchi** [comment] 2021-11-24 13:36
Tried and it works fine for me. We released an enhancement that solves this kind of problems https://github.com/Azure/vscode-kubernetes-tools/pull/924 . Now all CRDs are fetched from the active cluster. It could take a while if there are many operators installed but eventually the right intellisense should be activated.

![minio-intellisense](https://user-images.githubusercontent.com/49404737/143248341-6877e025-7b01-4583-9181-700849d09007.gif)

Closing it. Feel free to reopen it if you see some issue. Thanks!
.

**Closed by lstocchi** 2021-11-24 13:36 UTC
