### ISSUE TITLE
Command "Kubernetes exec" and "kubernetes terminal" throw errors "Couldn't find any relevant pods."

### ISSUE THREAD

**Issue by songkaiape** [Azure/vscode-kubernetes-tools#65] opened 2018-03-02 09:04 UTC
Repro steps:

1. open vscode with kubernetes plugin ,press F1, select "Kubernetes exec" or "kubernetes terminal"
2. type a command like bash 

Expect: a bash open in terminal 

Actual:
![image](https://user-images.githubusercontent.com/4318793/36890848-7339a96c-1e3a-11e8-9810-7cbf44ef9da4.png)

But I can open terminal by right click on the pod.
![image](https://user-images.githubusercontent.com/4318793/36890951-d914519c-1e3a-11e8-9435-31d82c10b804.png)

**Comment by bnookala** [comment] 2018-03-06 21:40
@songkaiape - right now, the exec/terminal commands are built around functionality that assumes your pods have a kubernetes label, `run` that is assigned to the name of the workspace open in visual studio code. 

@itowlson, @squillace I feel that this behavior should be changed, but I can't think of a ~ great ~ way to expose this. thoughts?

**Comment by itowlson** [comment] 2018-03-06 21:51
First off, apologies for not responding more promptly to this issue - and thanks @bnookala for addressing it.  It looks like this command was designed to tie into the way the specific way the extension launches deployments, which works beautifully when you live entirely within the extension, but tumbles to the ground in the broader scenario.

I agree the behaviour needs to be improved.  I suggest that we should still initially look for 'relevant' pods (possibly with a broader definition of 'relevance'), so that the in-extension workflow can be seamless, but if we don't find any then we should list all pods rather than just sulking.

cc @squillace, who ran into the same issue just yesterday...

**Closed** 2018-03-11 22:18 UTC
